version: '3'
services:
  web :
    build :
      context : .
      dockerfile : dockerfile
    ports :
      - "3041:3000"
    container_name: arsip-surat-elektronik
    networks :
      - arsip-surat-elektronik-network
    command : npm start

networks:
  arsip-surat-elektronik-network:
    driver : bridge
    
  